source :rubygems

gem 'cramp'

gem 'foreman'
gem 'thin'
gem 'haml'
gem 'json'

gem 'em-hiredis', :git => "git://github.com/mloughran/em-hiredis.git"

# Rack based routing
gem 'http_router'

# Collection of async-proof rack middlewares - https://github.com/rkh/async-rack.git
gem 'async-rack'
gem 'websocket-rack'

group :development do
  gem 'ruby-debug'
end
